[package]
name = "plotgram"
version = "0.1.0"
edition = "2024"
description = "Grammar of graphics for Rust"

[dependencies]
plotters = { version = "0.3", default-features = false, features = ["bitmap_backend", "line_series"] }
image = "0.24"
base64 = "0.22"
